### ISSUE TITLE
when i run the script it says 'y' is not defined in line 7. I am a beginner . Please help me

### ISSUE THREAD

**Issue by shune1** [SaveTheRbtz/ml-class#1]
function J = computeCost(X, y, theta)
%COMPUTECOST Compute cost for linear regression
%   J = COMPUTECOST(X, y, theta) computes the cost of using theta as the
%   parameter for linear regression to fit the data points in X and y

% Initialize some useful values
m = length(y); % number of training examples

% You need to return the following variables correctly 
J = 0;

% ====================== YOUR CODE HERE ======================
% Instructions: Compute the cost of a particular choice of theta
%               You should set J to the cost.

 J= 1/(2*m)* sum((X*theta-y).^2);

% =========================================================================

end
**_****_**

**Comment by SaveTheRbtz** [comment]
This is rather unlikely since `y` is defined as a function argument on line1.

Please refer to https://www.gnu.org/software/octave/doc/v4.0.3/Defining-Functions.html for formal function definition syntax.

**Comment by shune1** [comment]
Not sure. But when i tried running the script, it worked on the first try.
Then its giving me the same error again and again.

Do x,y and theta need to be defined beforehand with the values?
